### ISSUE TITLE
识别失败

### ISSUE THREAD

**Issue by Xmi12** [KimigaiiWuyi/Bangumi_Auto_Rename#14]
这是怎么回事呢？
![屏幕截图 2024-12-11 015015](https://github.com/user-attachments/assets/94861da3-dde6-4151-82b7-adf3b3c697a8)

**Comment by KimigaiiWuyi** [comment]
目前判断是电影还是番剧主要依据文件夹里面的文件数量
新番集数不够可能识别成电影了
后面可以出一个参数 强制指定是番剧还是电影

另外你的KEY漏了, 建议打个马赛克

**Comment by Xmi12** [comment]
> 目前判断是电影还是番剧主要依据文件夹里面的文件数量 新番集数不够可能识别成电影了 后面可以出一个参数 强制指定是番剧还是电影
> 
> 另外你的KEY漏了, 建议打个马赛克

好的大佬，不过qb自动任务也会这样
![Image_55000198869225](https://github.com/user-attachments/assets/513cecce-1817-47d6-ad41-6b3095731157)

**Comment by KimigaiiWuyi** [comment]
单集大概率不行的哦 你下vcb合集这种可以
以后会加单集识别模式

**Comment by Xmi12** [comment]
> 单集大概率不行的哦 你下vcb合集这种可以 以后会加单集识别模式

好的
