### ISSUE TITLE
希望兼容linux系统

### ISSUE THREAD

**Issue by squanbo** [KimigaiiWuyi/Bangumi_Auto_Rename#15]
使用linux系统进行下载及刮削，目前只有windows版本，希望可以在linux上也可以使用。

**Comment by KimigaiiWuyi** [comment]
linux的话可以使用.py源程序 使用 python直接执行命令也是可以的

**Comment by squanbo** [comment]
但是硬链接的输出形式是不是不一样？

**Comment by KimigaiiWuyi** [comment]
理论上linux也有硬链接，逻辑应该和windows一致

**Comment by squanbo** [comment]
尝试了一下，linux上也可以用，谢谢！
