### ISSUE TITLE
看来是某个API无法使用了?

### ISSUE THREAD

**Issue by qhel** [KimigaiiWuyi/Bangumi_Auto_Rename#4]
![屏幕截图 2024-08-07 224644](https://github.com/user-attachments/assets/abdbde6c-b0c9-47ea-b0f4-dd1d35b9f30d)

**Comment by KimigaiiWuyi** [comment]
咦 这很奇怪

**Comment by qhel** [comment]
> 咦 这很奇怪 我更新了一个新的版本，请使用最新版本查看是否正常 https://github.com/KimigaiiWuyi/Bangumi_Auto_Rename/releases/tag/v0.1.6

![image](https://github.com/user-attachments/assets/8e0a0f94-c91d-41a4-bab4-8dd4fb750fe9)
还是相同的错误😢

**Comment by KimigaiiWuyi** [comment]
我更换了打包方式，请再次下载新版本尝试一下
https://github.com/KimigaiiWuyi/Bangumi_Auto_Rename/releases/tag/v0.1.6

**Comment by qhel** [comment]
> 我更换了打包方式，请再次下载新版本尝试一下 https://github.com/KimigaiiWuyi/Bangumi_Auto_Rename/releases/tag/v0.1.6

![image](https://github.com/user-attachments/assets/ae64461a-6f75-4987-9477-1e5c4d2fb7e0)
还是一样的报错，系统版本如下
![image](https://github.com/user-attachments/assets/3d65e281-611f-4e1c-a78a-4782d0dbbbc3)

**Comment by KimigaiiWuyi** [comment]
#6
