### ISSUE TITLE
掃出一堆毒是否沒包好?

### ISSUE THREAD

**Issue by AruChen** [KimigaiiWuyi/Bangumi_Auto_Rename#5]
https://www.virustotal.com/gui/file/6cf4d79086d522ff5bac061c922d741f134e1eece404da1ea1246f58cbe62b7e?nocache=1

[screencapture-virustotal-gui-file-6cf4d79086d522ff5bac061c922d741f134e1eece404da1ea1246f58cbe62b7e-2024-08-30-10_39_30.pdf](https://github.com/user-attachments/files/16810754/screencapture-virustotal-gui-file-6cf4d79086d522ff5bac061c922d741f134e1eece404da1ea1246f58cbe62b7e-2024-08-30-10_39_30.pdf)

![screencapture-virustotal-gui-file-6cf4d79086d522ff5bac061c922d741f134e1eece404da1ea1246f58cbe62b7e-2024-08-30-10_39_30](https://github.com/user-attachments/assets/01a7b621-e662-4dec-9485-ff75ac7073e1)

**Comment by KimigaiiWuyi** [comment]
直接py文件打包,报毒正常;
源代码均已开源,可以直接使用`.py`文件调用,或者用其他py打包工具自行打包~
