### ISSUE TITLE
看起来似乎是jikanv3的api停止支持了？

### ISSUE THREAD

**Issue by Sparidae** [KimigaiiWuyi/Bangumi_Auto_Rename#6]
![image](https://github.com/user-attachments/assets/fc4e0e90-851e-4ddf-b0ff-15195cd4e1ce)

**Comment by KimigaiiWuyi** [comment]
挺奇怪的 我打包成exe就会出现这个问题
直接安装python环境并调用py脚本就不会

**Comment by Sparidae** [comment]
我看了代码调用jikan的部分，似乎可以直接无缝迁移？
https://github.com/abhinavk99/jikanpy 
这里更新了v4版本，库里面pyproject文件里面依赖还是v3版本

**Comment by KimigaiiWuyi** [comment]
pyproject里面的不是jikanpy>=4.3么

**Comment by Sparidae** [comment]
https://github.com/abhinavk99/jikanpy 里面v4的包名变成了jikanpy-v4，现在是1.0.2版本
![image](https://github.com/user-attachments/assets/1d1a3f4e-614b-4794-84ff-93f22f44d6b1)

**Comment by KimigaiiWuyi** [comment]
草...原来是这样吗 那就是我pyproject写错了
我重新打个包

**Comment by KimigaiiWuyi** [comment]
可以进行一下测试 https://github.com/KimigaiiWuyi/Bangumi_Auto_Rename/releases/tag/v0.1.7

**Comment by Sparidae** [comment]
非常感谢，但是似乎代码还是没更新？，我下载了0.17版本报错和之前一样

**Comment by KimigaiiWuyi** [comment]
> 非常感谢，但是似乎代码还是没更新？，我下载了0.17版本报错和之前一样

再试试?这次清除缓存编了一下
我代码还没push上去 所以git上看不到

**Comment by Sparidae** [comment]
非常感谢，可以正常运行了，很好用
